"""Sensible defaults used by the CLI ``sentinel init`` command and tests."""

from __future__ import annotations

from typing import Any

from sentinel.config.schema import ModelConfig, SentinelConfig


def default_config(model_name: str = "my_model") -> SentinelConfig:
    """Return a minimal valid `SentinelConfig`."""
    return SentinelConfig(model=ModelConfig(name=model_name))


def default_yaml_template(model_name: str = "my_model") -> str:
    """Return a heavily commented YAML template suitable for ``sentinel init``."""
    return f"""# Sentinel configuration
# Generated by `sentinel init`. Edit to suit your model.
version: "1.0"

model:
  name: {model_name}
  type: classification          # classification | regression | ranking | forecasting | generation
  domain: tabular               # tabular | timeseries | nlp | recommendation | graph
  framework: sklearn            # auto-detected if omitted

data_quality:
  schema:
    enforce: true
  freshness:
    max_age_hours: 24
  outlier_detection:
    method: iqr

drift:
  data:
    method: psi                 # psi | ks | js_divergence | chi_squared | wasserstein
    threshold: 0.2
    window: 7d
    reference: baseline

alerts:
  channels:
    - type: slack
      webhook_url: ${{SLACK_WEBHOOK_URL}}
      channel: "#ml-alerts"
  policies:
    cooldown: 1h
    digest_mode: false

audit:
  storage: local
  path: ./audit/
  log_predictions: false
  retention_days: 2555         # 7 years (FCA-compliant)

deployment:
  strategy: canary
  canary:
    initial_traffic_pct: 5
    ramp_steps: [5, 25, 50, 100]
    ramp_interval: 1h
"""


DEFAULT_PRICING: dict[str, dict[str, float]] = {
    # USD per 1k tokens — keep up to date with provider pricing
    "gpt-4o": {"input": 0.005, "output": 0.015},
    "gpt-4o-mini": {"input": 0.00015, "output": 0.0006},
    "gpt-4-turbo": {"input": 0.01, "output": 0.03},
    "claude-opus-4-6": {"input": 0.015, "output": 0.075},
    "claude-sonnet-4-6": {"input": 0.003, "output": 0.015},
    "claude-haiku-4-5": {"input": 0.0008, "output": 0.004},
    "text-embedding-3-small": {"input": 0.00002, "output": 0.0},
    "text-embedding-3-large": {"input": 0.00013, "output": 0.0},
    # Azure OpenAI — prefix deployment names with ``azure/`` so
    # customers can tell Azure-hosted calls apart from direct OpenAI
    # in their cost breakdowns. Prices track OpenAI's public list;
    # customers on enterprise agreements should override via the
    # ``llmops.token_economics.pricing`` config field.
    "azure/gpt-4o": {"input": 0.005, "output": 0.015},
    "azure/gpt-4o-mini": {"input": 0.00015, "output": 0.0006},
    "azure/gpt-4-turbo": {"input": 0.01, "output": 0.03},
    "azure/gpt-35-turbo": {"input": 0.0005, "output": 0.0015},
    "azure/text-embedding-3-small": {"input": 0.00002, "output": 0.0},
    "azure/text-embedding-3-large": {"input": 0.00013, "output": 0.0},
}


DEFAULT_HOOK_TIMEOUTS: dict[str, float] = {
    "guardrail": 1.0,
    "drift": 5.0,
    "notification": 2.0,
}


def get_default_pricing(model: str) -> dict[str, float] | None:
    """Look up default pricing for a known model."""
    return DEFAULT_PRICING.get(model)


def merge_dicts(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursive dict merge — used by config inheritance.

    `override` takes precedence over `base`. Lists are replaced wholesale,
    not concatenated.
    """
    result: dict[str, Any] = dict(base)
    for k, v in override.items():
        if k in result and isinstance(result[k], dict) and isinstance(v, dict):
            result[k] = merge_dicts(result[k], v)
        else:
            result[k] = v
    return result
